name: CI
on: [push, pull_request]

env:
  RUST_BACKTRACE: full
  RUSTFLAGS: -D warnings
  CARGO_TERM_VERBOSE: true

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [msrv, stable, beta, nightly, macos, windows]
        include:
          - build: msrv
            os: ubuntu-latest
            rust: 1.51.0
          - build: stable
            os: ubuntu-latest
            rust: stable
          - build: beta
            os: ubuntu-latest
            rust: beta
          - build: nightly
            os: ubuntu-latest
            rust: nightly
          - build: macos
            os: macos-latest
            rust: stable
          - build: windows
            os: windows-latest
            rust: stable
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Install Rust toolchain
      id: rust-toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
    - name: Update Cargo.lock
      run: cargo update
    - name: Cache cargo directories
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ steps.rust-toolchain.outputs.rustc_hash }}-test-${{ hashFiles('Cargo.lock') }}
        restore-keys: ${{ runner.os }}-${{ steps.rust-toolchain.outputs.rustc_hash }}-test-
    - name: Build
      run: cargo build
    - name: Test
      if: startsWith(matrix.build, 'msrv') == false
      run: cargo test
    - name: Build with stable features
      if: matrix.build != 'msrv'
      run: cargo build --features serde
    - name: Test with stable features
      if: startsWith(matrix.build, 'msrv') == false
      run: cargo test --features serde
    - name: Build with unstable features
      if: startsWith(matrix.build, 'msrv') == false
      run: cargo build --features unstable
    - name: Test with unstable features
      if: startsWith(matrix.build, 'msrv') == false
      run: cargo test --features unstable
    - name: Build with all features
      if: matrix.rust == 'nightly'
      run: cargo build --all-features
    - name: Test with all features
      if: matrix.rust == 'nightly'
      run: cargo test --all-features

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Install Rust toolchain
      id: rust-toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Update Cargo.lock
      run: cargo update
    - name: Cache cargo directories
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ steps.rust-toolchain.outputs.rustc_hash }}-lint-${{ hashFiles('Cargo.lock') }}
        restore-keys: ${{ runner.os }}-${{ steps.rust-toolchain.outputs.rustc_hash }}-lint-
    - name: Check clippy
      run: cargo clippy --features serde,unstable
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Check documentation
      run: cargo doc --features serde,unstable --no-deps

  miri:
    name: Miri
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Install Rust toolchain
      id: rust-toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: miri
    - name: Update Cargo.lock
      run: cargo update
    - name: Cache cargo directories
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/miri
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ steps.rust-toolchain.outputs.rustc_hash }}-miri-${{ hashFiles('Cargo.lock') }}
        restore-keys: ${{ runner.os }}-${{ steps.rust-toolchain.outputs.rustc_hash }}-miri-
    - name: Setup Miri
      run: cargo miri setup
    - name: Test with all features using Miri
      run: cargo miri test --all-features
